### ISSUE TITLE
Derive class not working for MOS2 

### ISSUE THREAD

**Issue by yveskini** [xpsi-group/xpsi#491]
alpha for MOS2 return None instead of being bound to  MOS1

class derive(Derive):
    global MOS1

    def __init__(self):
        pass

    def __call__(self, boundto, caller=None):
        return MOS1.instrument['alpha']

**Comment by thjsal** [comment]
Here is for example the error message if running the scripts from the J1231 Zenodo:

```
Traceback (most recent call last):
  File "/home/saltuomo/xpsi/J1231/zenodo/psr_J1231-1411_A_Complex_Case/J1231/STU/STU_NICER_XMM_hotel_prmcosi2/STU_modules/main_NxX_hotel_prmcosi2.py", line 513, in <module>
    likelihood.check(None, [-3.1869004623e+04], 1.0e-6, physical_points=[p])  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saltuomo/.conda/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.3.0b0-py3.12-linux-x86_64.egg/xpsi/utils.py", line 26, in decorator
    for msg in func(*args, **kwargs):
  File "/home/saltuomo/.conda/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.3.0b0-py3.12-linux-x86_64.egg/xpsi/Likelihood.py", line 613, in check
    lls.append(self.__call__(point,force=force_update))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saltuomo/.conda/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.3.0b0-py3.12-linux-x86_64.egg/xpsi/Likelihood.py", line 506, in __call__
    x = self._driver(force_update=force)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saltuomo/.conda/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.3.0b0-py3.12-linux-x86_64.egg/xpsi/Likelihood.py", line 350, in _driver
    signal.register(tuple(
  File "/home/saltuomo/.conda/envs/xpsi_py3/lib/python3.12/site-packages/xpsi-2.3.0b0-py3.12-linux-x86_64.egg/xpsi/Signal.py", line 439, in register
    self.signals = self._instrument(integrated,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saltuomo/xpsi/J1231/zenodo/psr_J1231-1411_A_Complex_Case/J1231/STU/STU_NICER_XMM_hotel_prmcosi2/STU_modules/CustomInstrument_readsparse_hotel.py", line 25, in __call__
    matrix = self.construct_matrix()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/saltuomo/xpsi/J1231/zenodo/psr_J1231-1411_A_Complex_Case/J1231/STU/STU_NICER_XMM_hotel_prmcosi2/STU_modules/CustomInstrument_readsparse_hotel.py", line 17, in construct_matrix
    matrix = self['alpha'] * self.matrix # * self['absolute_alpha']
```

**Comment by thjsal** [comment]
Okay, I found that this error replacing `self._instrument = deepcopy( instrument )` with the original `self._instrument = instrument`  in this line:
https://github.com/xpsi-group/xpsi/blob/98387f1739ec3c37f559e3ff1b3cef7cf1c2ef60/xpsi/Signal.py#L120
